version: "0.2"
services:
  host:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "7045-7049:7045-7049"
      - "8080:8080"
